### ISSUE TITLE
Check that /shutdown route does nothing on non-Werkzeug servers

### ISSUE THREAD

**Issue by karlorg** [karlorg/drunken-octo-avenger#11]
Just a reminder, when we have a version of the app with the `/shutdown` route deployed, make sure that route does not allow random visitors to kill the server.

... and more generally, verify (somehow) that all the testing 'helper' URLs do nothing on a production deployment, which requires working out how to distinguish a production deployment from a staging one.

**Comment by allanderek** [comment]
I at least just tried visiting: allanderek.pythonanywhere.com/shutdown and it gave me a 'method not allowed' message and the server was not shutdown.

If we merge my improve-tests branch, then the shutdown route would not even actually be in the production server as the shutdown route is added in 'manage.py' to test server and that only occurs when actually running tests. We could even do the same for the rest of the test routes, although it might be a bit more of a hassle because they typically actually perform some work.

We could, rather than have a decorator and still make it a route, we could just have a decorator that 'manage.py' interprets and adds the routes in the same way that it does for 'shutdown'.

**Comment by karlorg** [comment]
That's a nice solution :)

**Comment by allanderek** [comment]
Okay, if I ever remember, then I'll look into this solution.
