### ISSUE TITLE
sometimes get 'Pytest test failure!' randomly

### ISSUE THREAD

**Issue by karlorg** [karlorg/drunken-octo-avenger#75]
maybe a return code isn't what we expect?  I wonder if this is related to #74.

**Comment by allanderek** [comment]
Hmm, this is indeed annoying, will investigate.

**Comment by allanderek** [comment]
Ah, I see what has happened. When you introduced TESTSERVER_PORT, this meant that the browser_test was trying to access urls with the LIVESERVER_PORT and hence failing. In addition in `manage.py` the `run_test_with_server` command tries to shutdown the server by posting to `http://localhost:5000/shutdown`. This was why the casper tests were reported as failing because *that* was failing rather than the casper tests themselves.

I've fixed both.

**Comment by allanderek** [comment]
Just to be clear. For me the pytest tests were not "sometimes randomly" failing, but *consistently* every time failing. I think for you they were possibly "sometimes" failing because you sometimes had a debug server running in the background.

**Comment by karlorg** [comment]
Cool, good to have that sorted.
